### ISSUE TITLE
Register.pl fails to increment UID

### ISSUE THREAD

**Issue by jmsaurel** [IPGP/webobs#33]
It seems that register.pl fails incrementing the UID in case there is already a user registered with the same UID.

At line 154 of register.pl, SQL error does not seem captured correctly and ends up abruptly the registration process.
`$rv = $sth->execute($UID, $fullname, $login, $mailaddr);`

![Screenshot from 2019-09-25 06-56-54](https://user-images.githubusercontent.com/22295030/65576877-4b9ed400-df62-11e9-8e0a-86edc2cf2439.png)

**Comment by XavierBeguin** [comment]
Hi Jean-Marie,

My bad, it seems that when making sure database errors were correctly stopping the code in the scripts that use the DBI module, I overlooked this particular case where errors are expected and correctly handled (we check the return value of the `execute` method to know whether the UID already exist and we therefore don't want to raise errors).

Simply avoiding to raise the error with this database connection seems to do the trick:
```diff
--- register.pl.orig    2019-09-25 08:46:16.429580004 -0400
+++ register.pl 2019-09-25 08:46:43.558392800 -0400
@@ -142,7 +142,7 @@
                my $dbh = DBI->connect("dbi:SQLite:$WEBOBS{SQL_DB_USERS}", "", "", {
                        'AutoCommit' => 1,
                        'PrintError' => 1,
-                       'RaiseError' => 1,
+                       'RaiseError' => 0,
                        }) or die "Error connecting to $WEBOBS{SQL_DB_USERS}: $DBI::errstr" ;
                my $rv = 0;  # initial value for the loop
                my $nu = 1;  # number of tries
```

I've just made a test and this seems to work correctly this way.
I'll submit this correction in the repository right away.

**Comment by XavierBeguin** [comment]
Edit: the patch above will work, but be aware that an UID is already in use, the alternative UIDs will have the form `XB2`, `XB23`,  `XB234`, etc. instead of the expected `XB2`, `XB3`, `XB4` (this is a bug that I've just discovered).

Instead of committing the above simple patch, I took the opportunity (in my upcoming commit) to improve this part of the code and correctly verify whether an UID already exists in the database _before_ trying to insert the new user (I'm also fixing the bug about the alternative UID).
