### ISSUE TITLE
Ghost events on proc outputs

### ISSUE THREAD

**Issue by cyprien-griot** [IPGP/webobs#71]
Greetings all,

I am reporting a small issue concerning the GipsyX proc. We have indeed noticed that when we check GipsyX stations graphs for Mayotte, La Fournaise eruptions are somehow displayed : events only appear when we move the mouse over the graph (only the text note is displayed).

However the EVENTS_FILE parameter is not defined in the proc configuration. By default the parameter was commented, but I also tried to uncomment it without defining anything.

Thanks a lot in advance.

Regards,
Cyprien

**Comment by beaudu** [comment]
Dear Cyprien,

Thanks for detecting this issue. It concerns any proc's outputs and not only **gnss**, so I changed the title accordingly.

The script `/cgi-bin/showOUTG.pl` displays events as HTML mapping, if it finds a `.map` file in the `PATH_OUTG_GRAPHS` proc subdirectory with same basename as `.png` graph. This `.map` file is build by the superproc using `mkgraph.m` generic subfunction and output data from `plotevent.m`, **if** the `EVENTS_FILE` is defined **and** contains events.
That was the little bug: in your case you have defined the La Fournaise events in your GipsyX proc for a while, creating some map files for each time scales. When you have unset it, the files remained.

I will commit a fix in a moment. There is two possible workarounds for you:
- make and set a new event file for Mayotte containing at least one event (since an empty file will be ignored);
- delete manually (root privilege needed) the files in `/opt/webobs/OUTG/PROC.GIPSYX.../graphs/*.map`

F.

**Comment by cyprien-griot** [comment]
Hello François,
Thank you again for your great help. It worked perfectly.
Regards,
Cyprien
