### ISSUE TITLE
Have events appear on graphs

### ISSUE THREAD

**Issue by XavierBeguin** [IPGP/webobs#80]
I'm forwarding a request from our geochimist engineer: would it be possible to have events concerning a node appear on a genplot graph (e.g. in the shape of a vertical line on the graph)?

Use case: on source temperature graphs for a node, we'd like to be able to visualize the date when the data logger is changed to be able to explain any data offset due to the different data logger. (We are aware that being able to calibrate data loggers and correct the values would obviously be much better, but we don't have the means to calibrate data logger yet.) Thanks.

**Comment by beaudu** [comment]
Thanks Xavier.
Since v2.1.0, node events have a new option with a "sensor/data outcome" flag, that has been conceived exactly to make your request functional. The idea is that only events with this flag checked should appear on the graphs. This filter seems mandatory since many node events are only maintenance logs, but we can make it optional.
I propose to add the following parameters in future proc's configuration:
- `EVENTNODE_DISPLAY|Y`
- `EVENTNODE_OUTCOME_ONLY|Y`
and this functionnality might work for any type of proc (not only genplot), like `EVENTS_FILE` does.

**Comment by beaudu** [comment]
This feature request has been included in the v2.5. Variable names are a bit different than the above comment. See release notes.
